### ISSUE TITLE
Enhance Kentor to allow configuration sources to be modified

### ISSUE THREAD

**Issue by jamestelfer** [Sustainsys/authservices#771]
My company is currently using Kentor as the SAML SP for our product. In an upcoming release, we need to modify Kentor to enable the configuration to be looked up from a different source. This means that there will be engineering on this taking place over the next 6-8 weeks.

While we are relatively new to developing OSS, I'd like to do this work in the open in the same spirit as shown by this project, and develop it with a view that it could be accepted upstream.

Is this something that you would consider accepting upstream? If so, how can we best work with you on the design and implementation?

At this point, it looks like we would need to change the static methods on the `Options` class to do something like load a configuration service implementation class, defaulting to the current strategy. Since the API is currently static, this would be the least invasive change.

Possible options for specifying the implementation type would be to look it up using the MS service locator (not necessarily everyone's first choice) or to simply specify a type name on the `kentor.authServices` configuration element.

Also, if the configuration changes from being loaded once and cached statically, are there other places in the code that assume configuration stability?

Our specific requirement is around multi-tenancy: for a single system we need to enable different tenants to be able to supply their configuration via a UI, and we need to avoid the necessity to update this on the server configuration directly. I don't want to build too many assumptions on the source of configuration into Kentor itself though.

In theory, this kind of flexibility might help in other scenarios: for example storing certificates in Azure Key Storage instead of the Windows Certificate Store.

**Comment by explunit** [comment]
I'm not sure I fully understand the gap between what you're trying to do and what we see in these two issues:
1 - https://stackoverflow.com/questions/43980281/programatically-configure-sso-settings-using-kentor/43981285
2 - https://github.com/KentorIT/authservices/issues/335

Can you explain more?

But yes, this project does accept pull requests. I'm not the owner but I've contributed several enhancements & fixes. Be sure to read the [Contributing guidlines](https://github.com/KentorIT/authservices/blob/master/CONTRIBUTING.md) first.

**Comment by jamestelfer** [comment]
Thanks @explunit!

AFAICS the configuration is either set once at startup/first load or (in the case of the module) modifiable on a static field.

I'm working on a multi-tenant app, where:
* the application URL changes per tenant: i.e. `tenantname.app.com`
* each tenant may have its own SAML settings

Given that the application URL is different per tenant, this means that the return URL for a tenant would be different, as would the entity ID. It appears that I would need to make changes in order to allow a different configuration to be active on a per-request level.

This is how it appears to me, based on my inspection of the code and the issues you so kindly referenced.

An I missing something? Is there a straightforward approach to this?

Thanks!

**Comment by explunit** [comment]
So your question is not about configuring via code (vs. web.config) but rather configuring in a way that takes effect immediately without restarting application pool? Which mode are you using (HttpModule, MVC, or OWIN)?

**Comment by jamestelfer** [comment]
That's right. We're using the HttpModule at present.

The `Saml2AuthenticationModule` class defines its property as follows:
```
public static IOptions Options { get; set; } = Configuration.Options.FromConfiguration;
```

In the case where this can change from request to request, this might be expressed as:
```
public static Func<IOptions> Options { get; set; } = () => Configuration.Options.FromConfiguration;
```

It might be good also though to look at the `Options.FromConfiguration` call itself such that the ability to change configuration at runtime is more possible across a wider segment of the codebase.

To give an example of what I'm trying to achieve, take for example a multi-tenant app 'chooks.com' where there are two tenants, 'roosters.chooks.com' and 'hens.chooks.com'. Both domains point to the same web server. Each tenant though may have its own SAML configuration, each with a different entityID and return URL.

Given a request for `roosters.chooks.com`, I need to ensure that Kentor uses the roosters SAML config, but hens will need their own SAML configuration to be used.

**Comment by AndersAbel** [comment]
While the `IOptions` instance that is used can be changed during runtime, the AuthServices structure is not built to have different options per request.

The core `Kentor.AuthServices` library gets the option injected as a parameter, so if you use that directly you can have a per request setting. The HttpModule, MVC Controller and Owin middleware however are not built for per-request settings.

I'd suggest that you look at the Kentor.AuthServices.Mvc library for how to interact with the core `Kentor.AuthServices` library. It should be fairly simple to extend it to have a collection of `IOption` instances to use for each tenant.

**Comment by jamestelfer** [comment]
Thanks @AndersAbel I'll do this. The way we integrate Kentor is slightly different to normal, but fits your suggestion really well. I can adapt to a per-request model fairly easily.

Thanks for those who've replied to this issue, I really appreciate your time, and it's helped a lot.
