### ISSUE TITLE
AuthServices not working in asp.net application.

### ISSUE THREAD

**Issue by corsini2** [Sustainsys/authservices#785]
I am trying to integrate Authservices into an existing ASP.Net application.  I can run your sample application using the stupIDP, from my local machine.  But when I try to move the pieces into the existing application on our web server, I get "Unknown idp  http://stubidp.kentor.se/Metadata".  
Is there a common piece missing that could lead to this error?

**Comment by AndersAbel** [comment]
Looks like you've configured your application to not use the Stubidp but still tries to sign in using the StubIdp.
