### ISSUE TITLE
IdentityServer4 sample - SAML2 protocol implementation

### ISSUE THREAD

**Issue by Jenan** [Sustainsys/authservices#786]
Hello,

Are you planning create a samle for IdentityServer4 with .Net Core?

I am happy that is possible to use SAML2 with IdentityServer3 and it will be greate if will be wit IdentityServer4 as well. :)

Thank you

**Comment by AndersAbel** [comment]
There will be a sample with IdentityServer4, once there is a solution that supports it.

**Comment by Jenan** [comment]
What do you mean with solution that will be supported?

Thank you for clarification. :)

**Comment by Jenan** [comment]
OK, I see. Thank you.

**Comment by Jenan** [comment]
I can see the version on the .NET Core 2.0. - do you plan the sample for IdentityServer4?

**Comment by AndersAbel** [comment]
@Jenan Yes.
