### ISSUE TITLE
Found SAML response success but cannot login

### ISSUE THREAD

**Issue by avatart0ph** [Sustainsys/authservices#794]
Kentor returns null on var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync(); but in firefox, i found the SAML response with a success status code.

My worse case scenario is to write  write my own assertion but I am not giving up just yet on this tool kit. How do I configure Kentor to accept uid in attributes?

```
<saml2:AttributeStatement>
            <saml2:Attribute Name="uid"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                             >
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                      xsi:type="xs:string"
                                      >somevaluehere</saml2:AttributeValue>
            </saml2:Attribute>
        </saml2:AttributeStatement>
```
my code is
```
var attributeConsumingService = new AttributeConsumingService("AuthServices")
            {
                IsDefault = true,
            };
            

            attributeConsumingService.RequestedAttributes.Add(
                new RequestedAttribute("uid")
                {
                    IsRequired = true,
                });
```
is it also a problem if the idp is wso2?

**Comment by avatart0ph** [comment]
I figured that the Idp was giving the wrong EntityID. and changing it in .xml doesn't work.
So i changed it here and commented out the metadata location because if i change it in new EntityId it throws another error:

`var idp = new IdentityProvider(new EntityId("https://somethingidp/saml-sso"), spOptions)
            {
                //LoadMetadata = true,
                //MetadataLocation = "~/App_Data/IDPMetaData/idp.xml"
                AllowUnsolicitedAuthnResponse = true,
                Binding = Saml2BindingType.HttpRedirect,
                SingleSignOnServiceUrl = new Uri("https://somethingidp/saml-sso"),

            };`

But now I am getting a new error "The signing algorithm SHA1 is unknown or not supported by the current .NET Framework." with these configuration:
`MinIncomingSigningAlgorithm = "SHA1",
OutboundSigningAlgorithm = "SHA256"`

I am using .Net 4.5 so neither of the solutions work for me here https://github.com/Sustainsys/authservices/issues/717. 

I am using OWIN. Right now I'm telling the IdP admin to change it to sha256 hopefully that works.

**Comment by explunit** [comment]
why doesn't calling `Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures()` on startup work?

**Comment by explunit** [comment]
Sorry, ignore previous comment. I'm curious though... do you get a different message if you use `http://www.w3.org/2000/09/xmldsig#rsa-sha1` instead of `SHA1`?

**Comment by avatart0ph** [comment]
It returns this 
Message = "The signature verified correctly with the key contained in the signature, but that key is not trusted."

**Comment by explunit** [comment]
that sounds like a cert mismatch

**Comment by avatart0ph** [comment]
Just wondering how do you call `Kentor.AuthServices.Configuration.Options.GlobalEnableSha256XmlSignatures()` ? do i just place it in CreateSPOptions() (p.s. i am using the  sample owin project)

**Comment by avatart0ph** [comment]
I'm not sure if cert mismatch is the case because I already have the response with a success status code. It fails on /AuthServices/Acs

**Comment by explunit** [comment]
If you have not received the public key ahead of time (either through loading IDP metadata or configuring https://github.com/Sustainsys/authservices/blob/master/doc/Configuration.md#signingcertificate-element), you will get the error about untrusted key (even if the status says Success inside the SAML)

**Comment by avatart0ph** [comment]
I commented out the cert. It works now. I got it working but got another error.
https://github.com/Sustainsys/authservices/issues/238

Just wondering, does it have to be the same url as my application or can I use the production url i.e.
http://produrl.com/AuthServices ? it doesnt really state in the documentation

@explunit thank you for taking your time to help me out

**Comment by explunit** [comment]
Your entity id can be any URI value. it does not have to correspond to the real location of the application.

**Comment by avatart0ph** [comment]
thanks @explunit. it works now.

**Comment by explunit** [comment]
You're welcome.

**Comment by avatart0ph** [comment]
to anyone who was in the same boat as me,
using .Net4.5 and the idp returns sha1...
this works
`MinIncomingSigningAlgorithm = "http://www.w3.org/2000/09/xmldsig#rsa-sha1"`

and this is the propertery of SPOptions

**Comment by explunit** [comment]
Thanks. I have added this value to the documentation.

**Comment by rizwanmgm** [comment]
I am facing similar issue in google chrome and explorer var loginInfo = await AuthenticationManager.GetExternalLoginInfoAsync(); always null. can you help to solve this issue please.
