### ISSUE TITLE
Authenticating across multiple applications

### ISSUE THREAD

**Issue by BrianLytle** [Sustainsys/authservices#796]
I am using Kentor Authentication service within my MVC application (AppA) and it works great. However, I want to now be able to navigate to a different MVC application (AppB) from a link that is in AppA and avoid being sent to the IdP login page. My understanding was that the IdP would recognize that I had already logged in and simply redirect back to the requesting URL. Is that possible?

**Comment by explunit** [comment]
Yes, that's right. AppA and AppB should coordinate authentication only by depending on the same IDP. The IDP is responsible for remembering (e.g. via cookies) that the user is already authenticated and automatically redirecting back to AppB with the SAML response. There are some parameters where the RP (e.g. AppB) would request that the IDP re-authenticate the user, but I don't think that's the default flow.

**Comment by BrianLytle** [comment]
When I click on the link for AppB, I am always being redirected to the IdP Login Page (I am using the StubIdP for now). In AppB, how do I check to see if the user has already been Authenticated?

**Comment by explunit** [comment]
I haven't checked the code, but I suspect that the Stub IDP lacks the logic that a real IDP would have for detecting that the user is already authenticated.

**Comment by BrianLytle** [comment]
That would be a great answer! I will have to verify this once I have our
true IdP setup. Thanks for your help!!!

~ Brian

**Comment by explunit** [comment]
You're welcome.
