### ISSUE TITLE
Logout Response Not Signed Error

### ISSUE THREAD

**Issue by BrianLytle** [Sustainsys/authservices#801]
I am receiving an error telling me that the Logout Response is not signed, but it is. It is signed using SHA1 and I have the minIncomingSigningAlgorithm attribute of the kentor.authservices element set to SHA1. Any idea why I might be getting this error?

minIncomingSigningAlgorithm="SHA1"

**Comment by explunit** [comment]
Someone else reported that when running under .net 4.5 they had to use `http://www.w3.org/2000/09/xmldsig#rsa-sha1` instead of `SHA1` for minIncomingSigningAlgorithm. Could this be the issue?

**Comment by BrianLytle** [comment]
That wasn't my issue. Anders figured out my issue for me. There was not encryption on the incoming message. Thanks for your time Anders!!!
